// Code generated by honey. DO NOT EDIT.
package sdk

import (
	"context"
	"iter"
	"net/http"
)

// ParseSSEStreamExported exposes parseSSEStream for CLI consumption.
func ParseSSEStreamExported(ctx context.Context, resp *http.Response) iter.Seq2[SSEEvent, error] {
	return parseSSEStream(ctx, resp)
}
