// Code generated by honey. DO NOT EDIT.
package main

import (
	"fmt"
	"os"

	cli "github.com/anyrow/cli/internal/cli"
	"github.com/anyrow/cli/cmd"
)

func main() {
	if err := cmd.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(cli.ExitFor(err))
	}
}
