// Code generated by honey. DO NOT EDIT.
package cmd

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"slices"
	"strings"
	"time"

	"github.com/spf13/cobra"

	cli "github.com/anyrow/cli/internal/cli"
	sdk "github.com/anyrow/cli/internal/sdk"
)

var _ = bytes.NewReader
var _ = context.TODO
var _ = json.Marshal
var _ = fmt.Sprintf
var _ = io.Discard
var _ = http.MethodGet
var _ = url.PathEscape
var _ = os.Stdout
var _ = slices.Contains[[]string]
var _ = strings.NewReader
var _ = time.Second
var _ = sdk.SSEEvent{}
var _ = cli.Version

var batchCmd = &cobra.Command{
	Use:   "batch",
	Short: "List batches",
}

var batchListCmdProjectIdVar string
var batchListCmdCursorVar string
var batchListCmdFilterVar string
var batchListCmdLangVar string
var batchListCmdOrderVar string
var batchListCmdPageVar int64
var batchListCmdQVar string
var batchListCmdSelectVar string
var batchListCmdLimitVar int64
var batchListCmdStatusVar string

var batchListCmd = &cobra.Command{
	Use:   "list",
	Short: "List batches",
	PreRunE: func(cmd *cobra.Command, args []string) error {
		if cmd.Flags().Changed("status") && !slices.Contains([]string{"uploading", "processing", "merging", "complete", "partial", "failed"}, batchListCmdStatusVar) {
			return fmt.Errorf("--status must be one of: uploading, processing, merging, complete, partial, failed")
		}
		return nil
	},
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := batchListCmdProjectIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/batches"
		q := url.Values{}
		if cmd.Flags().Changed("cursor") { q.Set("cursor", batchListCmdCursorVar) }
		if cmd.Flags().Changed("filter") { q.Set("filter", batchListCmdFilterVar) }
		if cmd.Flags().Changed("lang") { q.Set("lang", batchListCmdLangVar) }
		if cmd.Flags().Changed("order") { q.Set("order", batchListCmdOrderVar) }
		if cmd.Flags().Changed("page") { q.Set("page", fmt.Sprintf("%d", batchListCmdPageVar)) }
		if cmd.Flags().Changed("q") { q.Set("q", batchListCmdQVar) }
		if cmd.Flags().Changed("select") { q.Set("select", batchListCmdSelectVar) }
		if cmd.Flags().Changed("limit") { q.Set("limit", fmt.Sprintf("%d", batchListCmdLimitVar)) }
		if cmd.Flags().Changed("status") { q.Set("status", batchListCmdStatusVar) }
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		req, rerr := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
		if rerr != nil { return rerr }
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

var batchGetCmdProjectIdVar string
var batchGetCmdBatchIdVar string

var batchGetCmd = &cobra.Command{
	Use:   "get",
	Short: "Get batch",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := batchGetCmdProjectIdVar
		batchID := batchGetCmdBatchIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/batches/" + url.PathEscape(batchID)
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		req, rerr := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
		if rerr != nil { return rerr }
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

var batchDownloadCsvCmdProjectIdVar string
var batchDownloadCsvCmdBatchIdVar string

var batchDownloadCsvCmd = &cobra.Command{
	Use:   "download-csv",
	Short: "Download batch CSV",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := batchDownloadCsvCmdProjectIdVar
		batchID := batchDownloadCsvCmdBatchIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/batches/" + url.PathEscape(batchID) + "/download/csv"
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		req, rerr := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
		if rerr != nil { return rerr }
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		return nil
	},
}

var batchDownloadJsonCmdProjectIdVar string
var batchDownloadJsonCmdBatchIdVar string

var batchDownloadJsonCmd = &cobra.Command{
	Use:   "download-json",
	Short: "Download batch JSON",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := batchDownloadJsonCmdProjectIdVar
		batchID := batchDownloadJsonCmdBatchIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/batches/" + url.PathEscape(batchID) + "/download/json"
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		req, rerr := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
		if rerr != nil { return rerr }
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		return nil
	},
}

var batchDownloadXlsxCmdProjectIdVar string
var batchDownloadXlsxCmdBatchIdVar string

var batchDownloadXlsxCmd = &cobra.Command{
	Use:   "download-xlsx",
	Short: "Download batch XLSX",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := batchDownloadXlsxCmdProjectIdVar
		batchID := batchDownloadXlsxCmdBatchIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/batches/" + url.PathEscape(batchID) + "/download/xlsx"
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		req, rerr := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
		if rerr != nil { return rerr }
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		return nil
	},
}

func init() {
	batchCmd.AddCommand(batchListCmd)
	batchCmd.AddCommand(batchGetCmd)
	batchCmd.AddCommand(batchDownloadCsvCmd)
	batchCmd.AddCommand(batchDownloadJsonCmd)
	batchCmd.AddCommand(batchDownloadXlsxCmd)
	/* Path flag — Use: "project_id" */
	batchListCmd.Flags().StringVar(&batchListCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	batchListCmd.MarkFlagRequired("project-id")
	batchListCmd.Flags().StringVar(&batchListCmdCursorVar, "cursor", "", "Query param cursor")
	batchListCmd.Flags().StringVar(&batchListCmdFilterVar, "filter", "", "Query param filter")
	batchListCmd.Flags().StringVar(&batchListCmdLangVar, "lang", "", "Query param lang")
	batchListCmd.Flags().StringVar(&batchListCmdOrderVar, "order", "", "Query param order")
	batchListCmd.Flags().Int64Var(&batchListCmdPageVar, "page", 0, "Query param page")
	batchListCmd.Flags().StringVar(&batchListCmdQVar, "q", "", "Query param q")
	batchListCmd.Flags().StringVar(&batchListCmdSelectVar, "select", "", "Query param select")
	batchListCmd.Flags().Int64Var(&batchListCmdLimitVar, "limit", 20, "Query param limit")
	batchListCmd.Flags().StringVar(&batchListCmdStatusVar, "status", "", "Query param status (one of: uploading, processing, merging, complete, partial, failed)")
	/* Path flag — Use: "project_id" */
	batchGetCmd.Flags().StringVar(&batchGetCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	batchGetCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "batch_id" */
	batchGetCmd.Flags().StringVar(&batchGetCmdBatchIdVar, "batch-id", "", "Path parameter batch_id")
	batchGetCmd.MarkFlagRequired("batch-id")
	/* Path flag — Use: "project_id" */
	batchDownloadCsvCmd.Flags().StringVar(&batchDownloadCsvCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	batchDownloadCsvCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "batch_id" */
	batchDownloadCsvCmd.Flags().StringVar(&batchDownloadCsvCmdBatchIdVar, "batch-id", "", "Path parameter batch_id")
	batchDownloadCsvCmd.MarkFlagRequired("batch-id")
	/* Path flag — Use: "project_id" */
	batchDownloadJsonCmd.Flags().StringVar(&batchDownloadJsonCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	batchDownloadJsonCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "batch_id" */
	batchDownloadJsonCmd.Flags().StringVar(&batchDownloadJsonCmdBatchIdVar, "batch-id", "", "Path parameter batch_id")
	batchDownloadJsonCmd.MarkFlagRequired("batch-id")
	/* Path flag — Use: "project_id" */
	batchDownloadXlsxCmd.Flags().StringVar(&batchDownloadXlsxCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	batchDownloadXlsxCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "batch_id" */
	batchDownloadXlsxCmd.Flags().StringVar(&batchDownloadXlsxCmdBatchIdVar, "batch-id", "", "Path parameter batch_id")
	batchDownloadXlsxCmd.MarkFlagRequired("batch-id")
}
