// Code generated by honey. DO NOT EDIT.
package cmd

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"slices"
	"strings"
	"time"

	"github.com/spf13/cobra"

	cli "github.com/anyrow/cli/internal/cli"
	sdk "github.com/anyrow/cli/internal/sdk"
)

var _ = bytes.NewReader
var _ = context.TODO
var _ = json.Marshal
var _ = fmt.Sprintf
var _ = io.Discard
var _ = http.MethodGet
var _ = url.PathEscape
var _ = os.Stdout
var _ = slices.Contains[[]string]
var _ = strings.NewReader
var _ = time.Second
var _ = sdk.SSEEvent{}
var _ = cli.Version

var columnCmd = &cobra.Command{
	Use:   "column",
	Short: "Add column",
}

var columnAddCmdProjectIdVar string
var columnAddCmdTableIdVar string
var columnAddCmdDataVar string

var columnAddCmd = &cobra.Command{
	Use:   "add",
	Short: "Add column",
	PreRunE: func(cmd *cobra.Command, args []string) error {
		if columnAddCmdDataVar == "" && !(false) {
			return fmt.Errorf("body required: pass --data or per-field flags")
		}
		return nil
	},
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := columnAddCmdProjectIdVar
		tableID := columnAddCmdTableIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/tables/" + url.PathEscape(tableID) + "/columns"
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		bodyBytes, derr := cli.ReadDataFlag(columnAddCmdDataVar)
		if derr != nil { return derr }
		req, rerr := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(bodyBytes))
		if rerr != nil { return rerr }
		req.Header.Set("Content-Type", "application/json")
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

var columnReorderCmdProjectIdVar string
var columnReorderCmdTableIdVar string
var columnReorderCmdDataVar string

var columnReorderCmd = &cobra.Command{
	Use:   "reorder",
	Short: "Reorder columns",
	PreRunE: func(cmd *cobra.Command, args []string) error {
		if columnReorderCmdDataVar == "" && !(false) {
			return fmt.Errorf("body required: pass --data or per-field flags")
		}
		return nil
	},
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := columnReorderCmdProjectIdVar
		tableID := columnReorderCmdTableIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/tables/" + url.PathEscape(tableID) + "/columns/order"
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		bodyBytes, derr := cli.ReadDataFlag(columnReorderCmdDataVar)
		if derr != nil { return derr }
		req, rerr := http.NewRequestWithContext(ctx, "PUT", reqURL, bytes.NewReader(bodyBytes))
		if rerr != nil { return rerr }
		req.Header.Set("Content-Type", "application/json")
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

var columnUpdateCmdProjectIdVar string
var columnUpdateCmdTableIdVar string
var columnUpdateCmdColIdVar string
var columnUpdateCmdDataVar string

var columnUpdateCmd = &cobra.Command{
	Use:   "update",
	Short: "Update column",
	PreRunE: func(cmd *cobra.Command, args []string) error {
		if columnUpdateCmdDataVar == "" && !(false) {
			return fmt.Errorf("body required: pass --data or per-field flags")
		}
		return nil
	},
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := columnUpdateCmdProjectIdVar
		tableID := columnUpdateCmdTableIdVar
		colID := columnUpdateCmdColIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/tables/" + url.PathEscape(tableID) + "/columns/" + url.PathEscape(colID)
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		bodyBytes, derr := cli.ReadDataFlag(columnUpdateCmdDataVar)
		if derr != nil { return derr }
		req, rerr := http.NewRequestWithContext(ctx, "PATCH", reqURL, bytes.NewReader(bodyBytes))
		if rerr != nil { return rerr }
		req.Header.Set("Content-Type", "application/json")
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

var columnRemoveCmdProjectIdVar string
var columnRemoveCmdTableIdVar string
var columnRemoveCmdColIdVar string

var columnRemoveCmd = &cobra.Command{
	Use:   "remove",
	Short: "Remove column",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := columnRemoveCmdProjectIdVar
		tableID := columnRemoveCmdTableIdVar
		colID := columnRemoveCmdColIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/tables/" + url.PathEscape(tableID) + "/columns/" + url.PathEscape(colID)
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		req, rerr := http.NewRequestWithContext(ctx, "DELETE", reqURL, nil)
		if rerr != nil { return rerr }
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

var columnDistinctCmdProjectIdVar string
var columnDistinctCmdTableIdVar string
var columnDistinctCmdColIdVar string
var columnDistinctCmdLimitVar int64
var columnDistinctCmdQVar string

var columnDistinctCmd = &cobra.Command{
	Use:   "distinct",
	Short: "Get distinct column values",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := columnDistinctCmdProjectIdVar
		tableID := columnDistinctCmdTableIdVar
		colID := columnDistinctCmdColIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/tables/" + url.PathEscape(tableID) + "/columns/" + url.PathEscape(colID) + "/distinct"
		q := url.Values{}
		if cmd.Flags().Changed("limit") { q.Set("limit", fmt.Sprintf("%d", columnDistinctCmdLimitVar)) }
		if cmd.Flags().Changed("q") { q.Set("q", columnDistinctCmdQVar) }
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		req, rerr := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
		if rerr != nil { return rerr }
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

func init() {
	columnCmd.AddCommand(columnAddCmd)
	columnCmd.AddCommand(columnReorderCmd)
	columnCmd.AddCommand(columnUpdateCmd)
	columnCmd.AddCommand(columnRemoveCmd)
	columnCmd.AddCommand(columnDistinctCmd)
	/* Path flag — Use: "project_id" */
	columnAddCmd.Flags().StringVar(&columnAddCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	columnAddCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "table_id" */
	columnAddCmd.Flags().StringVar(&columnAddCmdTableIdVar, "table-id", "", "Path parameter table_id")
	columnAddCmd.MarkFlagRequired("table-id")
	columnAddCmd.Flags().StringVar(&columnAddCmdDataVar, "data", "", "Request body: JSON literal, @file, or - for stdin")
	/* Path flag — Use: "project_id" */
	columnReorderCmd.Flags().StringVar(&columnReorderCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	columnReorderCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "table_id" */
	columnReorderCmd.Flags().StringVar(&columnReorderCmdTableIdVar, "table-id", "", "Path parameter table_id")
	columnReorderCmd.MarkFlagRequired("table-id")
	columnReorderCmd.Flags().StringVar(&columnReorderCmdDataVar, "data", "", "Request body: JSON literal, @file, or - for stdin")
	/* Path flag — Use: "project_id" */
	columnUpdateCmd.Flags().StringVar(&columnUpdateCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	columnUpdateCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "table_id" */
	columnUpdateCmd.Flags().StringVar(&columnUpdateCmdTableIdVar, "table-id", "", "Path parameter table_id")
	columnUpdateCmd.MarkFlagRequired("table-id")
	/* Path flag — Use: "col_id" */
	columnUpdateCmd.Flags().StringVar(&columnUpdateCmdColIdVar, "col-id", "", "Path parameter col_id")
	columnUpdateCmd.MarkFlagRequired("col-id")
	columnUpdateCmd.Flags().StringVar(&columnUpdateCmdDataVar, "data", "", "Request body: JSON literal, @file, or - for stdin")
	/* Path flag — Use: "project_id" */
	columnRemoveCmd.Flags().StringVar(&columnRemoveCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	columnRemoveCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "table_id" */
	columnRemoveCmd.Flags().StringVar(&columnRemoveCmdTableIdVar, "table-id", "", "Path parameter table_id")
	columnRemoveCmd.MarkFlagRequired("table-id")
	/* Path flag — Use: "col_id" */
	columnRemoveCmd.Flags().StringVar(&columnRemoveCmdColIdVar, "col-id", "", "Path parameter col_id")
	columnRemoveCmd.MarkFlagRequired("col-id")
	/* Path flag — Use: "project_id" */
	columnDistinctCmd.Flags().StringVar(&columnDistinctCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	columnDistinctCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "table_id" */
	columnDistinctCmd.Flags().StringVar(&columnDistinctCmdTableIdVar, "table-id", "", "Path parameter table_id")
	columnDistinctCmd.MarkFlagRequired("table-id")
	/* Path flag — Use: "col_id" */
	columnDistinctCmd.Flags().StringVar(&columnDistinctCmdColIdVar, "col-id", "", "Path parameter col_id")
	columnDistinctCmd.MarkFlagRequired("col-id")
	columnDistinctCmd.Flags().Int64Var(&columnDistinctCmdLimitVar, "limit", 100, "Query param limit")
	columnDistinctCmd.Flags().StringVar(&columnDistinctCmdQVar, "q", "", "Query param q")
}
