// Code generated by honey. DO NOT EDIT.
package cmd

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"slices"
	"strings"
	"time"

	"github.com/spf13/cobra"

	cli "github.com/anyrow/cli/internal/cli"
	sdk "github.com/anyrow/cli/internal/sdk"
)

var _ = bytes.NewReader
var _ = context.TODO
var _ = json.Marshal
var _ = fmt.Sprintf
var _ = io.Discard
var _ = http.MethodGet
var _ = url.PathEscape
var _ = os.Stdout
var _ = slices.Contains[[]string]
var _ = strings.NewReader
var _ = time.Second
var _ = sdk.SSEEvent{}
var _ = cli.Version

var exportCmd = &cobra.Command{
	Use:   "export",
	Short: "Get export status",
}

var exportGetCmdProjectIdVar string
var exportGetCmdExportIdVar string

var exportGetCmd = &cobra.Command{
	Use:   "get",
	Short: "Get export status",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := exportGetCmdProjectIdVar
		exportID := exportGetCmdExportIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/exports/" + url.PathEscape(exportID)
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		req, rerr := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
		if rerr != nil { return rerr }
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

func init() {
	exportCmd.AddCommand(exportGetCmd)
	/* Path flag — Use: "project_id" */
	exportGetCmd.Flags().StringVar(&exportGetCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	exportGetCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "export_id" */
	exportGetCmd.Flags().StringVar(&exportGetCmdExportIdVar, "export-id", "", "Path parameter export_id")
	exportGetCmd.MarkFlagRequired("export-id")
}
