// Code generated by honey. DO NOT EDIT.
package cmd

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"iter"
	"net/http"
	"net/url"
	"os"
	"slices"
	"strings"
	"time"

	"github.com/spf13/cobra"

	cli "github.com/anyrow/cli/internal/cli"
	sdk "github.com/anyrow/cli/internal/sdk"
)

var _ = bytes.NewReader
var _ = context.TODO
var _ = json.Marshal
var _ = fmt.Sprintf
var _ = io.Discard
var _ = http.MethodGet
var _ = url.PathEscape
var _ = os.Stdout
var _ = slices.Contains[[]string]
var _ = strings.NewReader
var _ = time.Second
var _ = sdk.SSEEvent{}
var _ = cli.Version
var _ iter.Seq2[cli.SSEEvent, error]

var extractCmd = &cobra.Command{
	Use:   "extract",
	Short: "Extract data from text or file (JSON response)",
}

var extractOnceCmdProjectIdVar string
var extractOnceCmdColumnsVar string
var extractOnceCmdInstructionVar string
var extractOnceCmdSchemaVar string
var extractOnceCmdStrictnessVar string
var extractOnceCmdTextVar string
var extractOnceCmdFileVar string

var extractOnceCmd = &cobra.Command{
	Use:   "once",
	Short: "Extract data from text or file (JSON response)",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := extractOnceCmdProjectIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/extract"
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		fields := map[string]string{}
		if cmd.Flags().Changed("columns") { fields["columns"] = extractOnceCmdColumnsVar }
		if cmd.Flags().Changed("instruction") { fields["instruction"] = extractOnceCmdInstructionVar }
		if cmd.Flags().Changed("schema") { fields["schema"] = extractOnceCmdSchemaVar }
		if cmd.Flags().Changed("strictness") { fields["strictness"] = extractOnceCmdStrictnessVar }
		if cmd.Flags().Changed("text") { fields["text"] = extractOnceCmdTextVar }
		files := map[string]string{}
		if extractOnceCmdFileVar != "" { files["file"] = extractOnceCmdFileVar }
		mpReader, mpCT, mpErr := cli.BuildMultipart(fields, files)
		if mpErr != nil { return mpErr }
		_ = mpCT
		req, rerr := http.NewRequestWithContext(ctx, "POST", reqURL, mpReader)
		if rerr != nil { return rerr }
		req.Header.Set("Content-Type", mpCT) // multipart/form-data; boundary=...
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

var extractStreamCmdProjectIdVar string
var extractStreamCmdColumnsVar string
var extractStreamCmdInstructionVar string
var extractStreamCmdSchemaVar string
var extractStreamCmdStrictnessVar string
var extractStreamCmdTextVar string
var extractStreamCmdFileVar string

var extractStreamCmd = &cobra.Command{
	Use:   "stream",
	Short: "Extract data from text or file (SSE stream)",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := extractStreamCmdProjectIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/extract-stream"
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		fields := map[string]string{}
		if cmd.Flags().Changed("columns") { fields["columns"] = extractStreamCmdColumnsVar }
		if cmd.Flags().Changed("instruction") { fields["instruction"] = extractStreamCmdInstructionVar }
		if cmd.Flags().Changed("schema") { fields["schema"] = extractStreamCmdSchemaVar }
		if cmd.Flags().Changed("strictness") { fields["strictness"] = extractStreamCmdStrictnessVar }
		if cmd.Flags().Changed("text") { fields["text"] = extractStreamCmdTextVar }
		files := map[string]string{}
		if extractStreamCmdFileVar != "" { files["file"] = extractStreamCmdFileVar }
		mpReader, mpCT, mpErr := cli.BuildMultipart(fields, files)
		if mpErr != nil { return mpErr }
		_ = mpCT
		req, rerr := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
		if rerr != nil { return rerr }
		req.Header.Set("Accept", "text/event-stream")
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		it := sdk.ParseSSEStreamExported(ctx, resp)
		wrapped := func(yield func(cli.SSEEvent, error) bool) {
			for ev, iterErr := range it {
				if !yield(cli.SSEEvent{Data: ev.Data, Event: ev.Event, ID: ev.ID, Retry: ev.Retry}, iterErr) {
					return
				}
			}
		}
		return cli.StreamSSE(wrapped, os.Stdout, cfg.Output)
	},
}

var extractTableOnceCmdProjectIdVar string
var extractTableOnceCmdTableIdVar string
var extractTableOnceCmdTextVar string
var extractTableOnceCmdFileVar string

var extractTableOnceCmd = &cobra.Command{
	Use:   "table-once",
	Short: "Extract into table (JSON response)",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := extractTableOnceCmdProjectIdVar
		tableID := extractTableOnceCmdTableIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/tables/" + url.PathEscape(tableID) + "/extract"
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		fields := map[string]string{}
		if cmd.Flags().Changed("text") { fields["text"] = extractTableOnceCmdTextVar }
		files := map[string]string{}
		if extractTableOnceCmdFileVar != "" { files["file"] = extractTableOnceCmdFileVar }
		mpReader, mpCT, mpErr := cli.BuildMultipart(fields, files)
		if mpErr != nil { return mpErr }
		_ = mpCT
		req, rerr := http.NewRequestWithContext(ctx, "POST", reqURL, mpReader)
		if rerr != nil { return rerr }
		req.Header.Set("Content-Type", mpCT) // multipart/form-data; boundary=...
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

var extractTableStreamCmdProjectIdVar string
var extractTableStreamCmdTableIdVar string
var extractTableStreamCmdTextVar string
var extractTableStreamCmdFileVar string

var extractTableStreamCmd = &cobra.Command{
	Use:   "table-stream",
	Short: "Extract into table (SSE stream)",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := extractTableStreamCmdProjectIdVar
		tableID := extractTableStreamCmdTableIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/tables/" + url.PathEscape(tableID) + "/extract-stream"
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		fields := map[string]string{}
		if cmd.Flags().Changed("text") { fields["text"] = extractTableStreamCmdTextVar }
		files := map[string]string{}
		if extractTableStreamCmdFileVar != "" { files["file"] = extractTableStreamCmdFileVar }
		mpReader, mpCT, mpErr := cli.BuildMultipart(fields, files)
		if mpErr != nil { return mpErr }
		_ = mpCT
		req, rerr := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
		if rerr != nil { return rerr }
		req.Header.Set("Accept", "text/event-stream")
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		it := sdk.ParseSSEStreamExported(ctx, resp)
		wrapped := func(yield func(cli.SSEEvent, error) bool) {
			for ev, iterErr := range it {
				if !yield(cli.SSEEvent{Data: ev.Data, Event: ev.Event, ID: ev.ID, Retry: ev.Retry}, iterErr) {
					return
				}
			}
		}
		return cli.StreamSSE(wrapped, os.Stdout, cfg.Output)
	},
}

func init() {
	extractCmd.AddCommand(extractOnceCmd)
	extractCmd.AddCommand(extractStreamCmd)
	extractCmd.AddCommand(extractTableOnceCmd)
	extractCmd.AddCommand(extractTableStreamCmd)
	/* Path flag — Use: "project_id" */
	extractOnceCmd.Flags().StringVar(&extractOnceCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	extractOnceCmd.MarkFlagRequired("project-id")
	extractOnceCmd.Flags().StringVar(&extractOnceCmdColumnsVar, "columns", "", "Body field columns")
	extractOnceCmd.Flags().StringVar(&extractOnceCmdInstructionVar, "instruction", "", "Body field instruction")
	extractOnceCmd.Flags().StringVar(&extractOnceCmdSchemaVar, "schema", "", "Body field schema")
	extractOnceCmd.Flags().StringVar(&extractOnceCmdStrictnessVar, "strictness", "", "Body field strictness (one of: strict, balanced, flexible)")
	extractOnceCmd.Flags().StringVar(&extractOnceCmdTextVar, "text", "", "Body field text")
	extractOnceCmd.Flags().StringVar(&extractOnceCmdFileVar, "file", "", "Path to file to upload")
	/* Path flag — Use: "project_id" */
	extractStreamCmd.Flags().StringVar(&extractStreamCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	extractStreamCmd.MarkFlagRequired("project-id")
	extractStreamCmd.Flags().StringVar(&extractStreamCmdColumnsVar, "columns", "", "Body field columns")
	extractStreamCmd.Flags().StringVar(&extractStreamCmdInstructionVar, "instruction", "", "Body field instruction")
	extractStreamCmd.Flags().StringVar(&extractStreamCmdSchemaVar, "schema", "", "Body field schema")
	extractStreamCmd.Flags().StringVar(&extractStreamCmdStrictnessVar, "strictness", "", "Body field strictness (one of: strict, balanced, flexible)")
	extractStreamCmd.Flags().StringVar(&extractStreamCmdTextVar, "text", "", "Body field text")
	extractStreamCmd.Flags().StringVar(&extractStreamCmdFileVar, "file", "", "Path to file to upload")
	/* Path flag — Use: "project_id" */
	extractTableOnceCmd.Flags().StringVar(&extractTableOnceCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	extractTableOnceCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "table_id" */
	extractTableOnceCmd.Flags().StringVar(&extractTableOnceCmdTableIdVar, "table-id", "", "Path parameter table_id")
	extractTableOnceCmd.MarkFlagRequired("table-id")
	extractTableOnceCmd.Flags().StringVar(&extractTableOnceCmdTextVar, "text", "", "Body field text")
	extractTableOnceCmd.Flags().StringVar(&extractTableOnceCmdFileVar, "file", "", "Path to file to upload")
	/* Path flag — Use: "project_id" */
	extractTableStreamCmd.Flags().StringVar(&extractTableStreamCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	extractTableStreamCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "table_id" */
	extractTableStreamCmd.Flags().StringVar(&extractTableStreamCmdTableIdVar, "table-id", "", "Path parameter table_id")
	extractTableStreamCmd.MarkFlagRequired("table-id")
	extractTableStreamCmd.Flags().StringVar(&extractTableStreamCmdTextVar, "text", "", "Body field text")
	extractTableStreamCmd.Flags().StringVar(&extractTableStreamCmdFileVar, "file", "", "Path to file to upload")
}
