// Code generated by honey. DO NOT EDIT.
package cmd

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"slices"
	"strings"
	"time"

	"github.com/spf13/cobra"

	cli "github.com/anyrow/cli/internal/cli"
	sdk "github.com/anyrow/cli/internal/sdk"
)

var _ = bytes.NewReader
var _ = context.TODO
var _ = json.Marshal
var _ = fmt.Sprintf
var _ = io.Discard
var _ = http.MethodGet
var _ = url.PathEscape
var _ = os.Stdout
var _ = slices.Contains[[]string]
var _ = strings.NewReader
var _ = time.Second
var _ = sdk.SSEEvent{}
var _ = cli.Version

var extractCmd = &cobra.Command{
	Use:   "extract",
	Short: "Extract data from text or file (JSON response)",
}

var extractOnceCmdProjectIdVar string

var extractOnceCmd = &cobra.Command{
	Use:   "once",
	Short: "Extract data from text or file (JSON response)",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := extractOnceCmdProjectIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/extract"
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		req, rerr := http.NewRequestWithContext(ctx, "POST", reqURL, nil)
		if rerr != nil { return rerr }
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

var extractStreamCmdProjectIdVar string

var extractStreamCmd = &cobra.Command{
	Use:   "stream",
	Short: "Extract data from text or file (SSE stream)",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := extractStreamCmdProjectIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/extract-stream"
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		req, rerr := http.NewRequestWithContext(ctx, "POST", reqURL, nil)
		if rerr != nil { return rerr }
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		return nil
	},
}

var extractTableOnceCmdProjectIdVar string
var extractTableOnceCmdTableIdVar string

var extractTableOnceCmd = &cobra.Command{
	Use:   "table-once",
	Short: "Extract into table (JSON response)",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := extractTableOnceCmdProjectIdVar
		tableID := extractTableOnceCmdTableIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/tables/" + url.PathEscape(tableID) + "/extract"
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		req, rerr := http.NewRequestWithContext(ctx, "POST", reqURL, nil)
		if rerr != nil { return rerr }
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

var extractTableStreamCmdProjectIdVar string
var extractTableStreamCmdTableIdVar string

var extractTableStreamCmd = &cobra.Command{
	Use:   "table-stream",
	Short: "Extract into table (SSE stream)",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := extractTableStreamCmdProjectIdVar
		tableID := extractTableStreamCmdTableIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/tables/" + url.PathEscape(tableID) + "/extract-stream"
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		req, rerr := http.NewRequestWithContext(ctx, "POST", reqURL, nil)
		if rerr != nil { return rerr }
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		return nil
	},
}

func init() {
	extractCmd.AddCommand(extractOnceCmd)
	extractCmd.AddCommand(extractStreamCmd)
	extractCmd.AddCommand(extractTableOnceCmd)
	extractCmd.AddCommand(extractTableStreamCmd)
	/* Path flag — Use: "project_id" */
	extractOnceCmd.Flags().StringVar(&extractOnceCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	extractOnceCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "project_id" */
	extractStreamCmd.Flags().StringVar(&extractStreamCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	extractStreamCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "project_id" */
	extractTableOnceCmd.Flags().StringVar(&extractTableOnceCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	extractTableOnceCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "table_id" */
	extractTableOnceCmd.Flags().StringVar(&extractTableOnceCmdTableIdVar, "table-id", "", "Path parameter table_id")
	extractTableOnceCmd.MarkFlagRequired("table-id")
	/* Path flag — Use: "project_id" */
	extractTableStreamCmd.Flags().StringVar(&extractTableStreamCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	extractTableStreamCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "table_id" */
	extractTableStreamCmd.Flags().StringVar(&extractTableStreamCmdTableIdVar, "table-id", "", "Path parameter table_id")
	extractTableStreamCmd.MarkFlagRequired("table-id")
}
