// Code generated by honey. DO NOT EDIT.
package cmd

import (
	"context"
	"fmt"
	"os"

	"github.com/spf13/cobra"

	cli "github.com/anyrow/cli/internal/cli"
)

var _ = fmt.Sprintf
var _ = os.Exit

// EnvPrefix is the prefix used for all <PREFIX>_<FLAG> environment variables.
const EnvPrefix = "ANYROW"

// ConfigName is the directory name under $XDG_CONFIG_HOME / ~/.config for the config file.
const ConfigName = "anyrow"

// DefaultBaseURL is used when neither --base-url, env var, nor the config file provide one.
const DefaultBaseURL = "https://api.anyrow.ai"

type configKey struct{}

// runtimeConfig is the resolved CLI config stashed on the cobra context.
type runtimeConfig struct {
	Cfg cli.Config
}

// rootCmd is the top-level cobra command for the anyrow CLI.
var rootCmd = &cobra.Command{
	Use:     "anyrow",
	Short:   "anyrow CLI",
	Version: cli.Version,
	SilenceUsage: true,
	PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
		cfg, err := cli.LoadConfig(cmd.Flags(), EnvPrefix, ConfigName)
		if err != nil {
			return err
		}
		if cfg.BaseURL == "" {
			cfg.BaseURL = DefaultBaseURL
		}
		ctx := context.WithValue(cmd.Context(), configKey{}, runtimeConfig{Cfg: cfg})
		cmd.SetContext(ctx)
		return nil
	},
}

// Execute runs the root command.
func Execute() error {
	return rootCmd.Execute()
}

func configFromCtx(ctx context.Context) cli.Config {
	if v, ok := ctx.Value(configKey{}).(runtimeConfig); ok {
		return v.Cfg
	}
	return cli.Config{}
}

func init() {
	rootCmd.PersistentFlags().String("api-key", "", "API key (overrides env + config file)")
	rootCmd.PersistentFlags().String("base-url", "", "Override API base URL")
	rootCmd.PersistentFlags().String("output", "json", "Output mode: json|ndjson|yaml|table")
	rootCmd.PersistentFlags().Bool("verbose", false, "Print request metadata to stderr")
	rootCmd.PersistentFlags().String("config", "", "Path to config file")
	rootCmd.PersistentFlags().String("timeout", "30s", "Request timeout (Go duration)")
	rootCmd.AddCommand(batchCmd)
	rootCmd.AddCommand(columnCmd)
	rootCmd.AddCommand(exportCmd)
	rootCmd.AddCommand(extractCmd)
	rootCmd.AddCommand(rowCmd)
	rootCmd.AddCommand(suggestCmd)
	rootCmd.AddCommand(tableCmd)
	rootCmd.AddCommand(tableTemplateCmd)
	rootCmd.AddCommand(webhookCmd)
}
