// Code generated by honey. DO NOT EDIT.
package cmd

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"slices"
	"strings"
	"time"

	"github.com/spf13/cobra"

	cli "github.com/anyrow/cli/internal/cli"
	sdk "github.com/anyrow/cli/internal/sdk"
)

var _ = bytes.NewReader
var _ = context.TODO
var _ = json.Marshal
var _ = fmt.Sprintf
var _ = io.Discard
var _ = http.MethodGet
var _ = url.PathEscape
var _ = os.Stdout
var _ = slices.Contains[[]string]
var _ = strings.NewReader
var _ = time.Second
var _ = sdk.SSEEvent{}
var _ = cli.Version

var rowCmd = &cobra.Command{
	Use:   "row",
	Short: "List rows",
}

var rowListCmdProjectIdVar string
var rowListCmdTableIdVar string
var rowListCmdCursorVar string
var rowListCmdFilterVar string
var rowListCmdLimitVar int64
var rowListCmdOrderVar string
var rowListCmdPageVar int64
var rowListCmdQVar string

var rowListCmd = &cobra.Command{
	Use:   "list",
	Short: "List rows",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := rowListCmdProjectIdVar
		tableID := rowListCmdTableIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/tables/" + url.PathEscape(tableID) + "/rows"
		q := url.Values{}
		if cmd.Flags().Changed("cursor") { q.Set("cursor", rowListCmdCursorVar) }
		if cmd.Flags().Changed("filter") { q.Set("filter", rowListCmdFilterVar) }
		if cmd.Flags().Changed("limit") { q.Set("limit", fmt.Sprintf("%d", rowListCmdLimitVar)) }
		if cmd.Flags().Changed("order") { q.Set("order", rowListCmdOrderVar) }
		if cmd.Flags().Changed("page") { q.Set("page", fmt.Sprintf("%d", rowListCmdPageVar)) }
		if cmd.Flags().Changed("q") { q.Set("q", rowListCmdQVar) }
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		req, rerr := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
		if rerr != nil { return rerr }
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

var rowCreateCmdProjectIdVar string
var rowCreateCmdTableIdVar string
var rowCreateCmdDataVar string

var rowCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create row",
	PreRunE: func(cmd *cobra.Command, args []string) error {
		if rowCreateCmdDataVar == "" && !(false) {
			return fmt.Errorf("body required: pass --data or per-field flags")
		}
		return nil
	},
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := rowCreateCmdProjectIdVar
		tableID := rowCreateCmdTableIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/tables/" + url.PathEscape(tableID) + "/rows"
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		// merge --data + per-prop flags
		merged := map[string]any{}
		if rowCreateCmdDataVar != "" {
			dataBytes, derr := cli.ReadDataFlag(rowCreateCmdDataVar)
			if derr != nil { return derr }
			if len(dataBytes) > 0 {
				if jerr := json.Unmarshal(dataBytes, &merged); jerr != nil { return fmt.Errorf("parse --data: %w", jerr) }
			}
		}
		bodyBytes, merr := json.Marshal(merged)
		if merr != nil { return merr }
		req, rerr := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(bodyBytes))
		if rerr != nil { return rerr }
		req.Header.Set("Content-Type", "application/json")
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

var rowAggregateCmdProjectIdVar string
var rowAggregateCmdTableIdVar string
var rowAggregateCmdAggsVar string
var rowAggregateCmdFilterVar string

var rowAggregateCmd = &cobra.Command{
	Use:   "aggregate",
	Short: "Aggregate column values",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := rowAggregateCmdProjectIdVar
		tableID := rowAggregateCmdTableIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/tables/" + url.PathEscape(tableID) + "/rows/aggregate"
		q := url.Values{}
		q.Set("aggs", rowAggregateCmdAggsVar)
		if cmd.Flags().Changed("filter") { q.Set("filter", rowAggregateCmdFilterVar) }
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		req, rerr := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
		if rerr != nil { return rerr }
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

var rowBulkCmdProjectIdVar string
var rowBulkCmdTableIdVar string
var rowBulkCmdDataVar string

var rowBulkCmd = &cobra.Command{
	Use:   "bulk",
	Short: "Bulk create/update/delete rows",
	PreRunE: func(cmd *cobra.Command, args []string) error {
		if rowBulkCmdDataVar == "" && !(false) {
			return fmt.Errorf("body required: pass --data or per-field flags")
		}
		return nil
	},
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := rowBulkCmdProjectIdVar
		tableID := rowBulkCmdTableIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/tables/" + url.PathEscape(tableID) + "/rows/bulk"
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		bodyBytes, derr := cli.ReadDataFlag(rowBulkCmdDataVar)
		if derr != nil { return derr }
		req, rerr := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(bodyBytes))
		if rerr != nil { return rerr }
		req.Header.Set("Content-Type", "application/json")
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

var rowGetCmdProjectIdVar string
var rowGetCmdTableIdVar string
var rowGetCmdRowIdVar string

var rowGetCmd = &cobra.Command{
	Use:   "get",
	Short: "Get row",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := rowGetCmdProjectIdVar
		tableID := rowGetCmdTableIdVar
		rowID := rowGetCmdRowIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/tables/" + url.PathEscape(tableID) + "/rows/" + url.PathEscape(rowID)
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		req, rerr := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
		if rerr != nil { return rerr }
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

var rowUpdateCmdProjectIdVar string
var rowUpdateCmdTableIdVar string
var rowUpdateCmdRowIdVar string
var rowUpdateCmdDataVar string

var rowUpdateCmd = &cobra.Command{
	Use:   "update",
	Short: "Update row",
	PreRunE: func(cmd *cobra.Command, args []string) error {
		if rowUpdateCmdDataVar == "" && !(false) {
			return fmt.Errorf("body required: pass --data or per-field flags")
		}
		return nil
	},
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := rowUpdateCmdProjectIdVar
		tableID := rowUpdateCmdTableIdVar
		rowID := rowUpdateCmdRowIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/tables/" + url.PathEscape(tableID) + "/rows/" + url.PathEscape(rowID)
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		// merge --data + per-prop flags
		merged := map[string]any{}
		if rowUpdateCmdDataVar != "" {
			dataBytes, derr := cli.ReadDataFlag(rowUpdateCmdDataVar)
			if derr != nil { return derr }
			if len(dataBytes) > 0 {
				if jerr := json.Unmarshal(dataBytes, &merged); jerr != nil { return fmt.Errorf("parse --data: %w", jerr) }
			}
		}
		bodyBytes, merr := json.Marshal(merged)
		if merr != nil { return merr }
		req, rerr := http.NewRequestWithContext(ctx, "PATCH", reqURL, bytes.NewReader(bodyBytes))
		if rerr != nil { return rerr }
		req.Header.Set("Content-Type", "application/json")
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

var rowDeleteCmdProjectIdVar string
var rowDeleteCmdTableIdVar string
var rowDeleteCmdRowIdVar string

var rowDeleteCmd = &cobra.Command{
	Use:   "delete",
	Short: "Delete row",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := rowDeleteCmdProjectIdVar
		tableID := rowDeleteCmdTableIdVar
		rowID := rowDeleteCmdRowIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/tables/" + url.PathEscape(tableID) + "/rows/" + url.PathEscape(rowID)
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		req, rerr := http.NewRequestWithContext(ctx, "DELETE", reqURL, nil)
		if rerr != nil { return rerr }
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

func init() {
	rowCmd.AddCommand(rowListCmd)
	rowCmd.AddCommand(rowCreateCmd)
	rowCmd.AddCommand(rowAggregateCmd)
	rowCmd.AddCommand(rowBulkCmd)
	rowCmd.AddCommand(rowGetCmd)
	rowCmd.AddCommand(rowUpdateCmd)
	rowCmd.AddCommand(rowDeleteCmd)
	/* Path flag — Use: "project_id" */
	rowListCmd.Flags().StringVar(&rowListCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	rowListCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "table_id" */
	rowListCmd.Flags().StringVar(&rowListCmdTableIdVar, "table-id", "", "Path parameter table_id")
	rowListCmd.MarkFlagRequired("table-id")
	rowListCmd.Flags().StringVar(&rowListCmdCursorVar, "cursor", "", "Query param cursor")
	rowListCmd.Flags().StringVar(&rowListCmdFilterVar, "filter", "", "Query param filter")
	rowListCmd.Flags().Int64Var(&rowListCmdLimitVar, "limit", 20, "Query param limit")
	rowListCmd.Flags().StringVar(&rowListCmdOrderVar, "order", "", "Query param order")
	rowListCmd.Flags().Int64Var(&rowListCmdPageVar, "page", 0, "Query param page")
	rowListCmd.Flags().StringVar(&rowListCmdQVar, "q", "", "Query param q")
	/* Path flag — Use: "project_id" */
	rowCreateCmd.Flags().StringVar(&rowCreateCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	rowCreateCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "table_id" */
	rowCreateCmd.Flags().StringVar(&rowCreateCmdTableIdVar, "table-id", "", "Path parameter table_id")
	rowCreateCmd.MarkFlagRequired("table-id")
	rowCreateCmd.Flags().StringVar(&rowCreateCmdDataVar, "data", "", "Request body: JSON literal, @file, or - for stdin")
	/* Path flag — Use: "project_id" */
	rowAggregateCmd.Flags().StringVar(&rowAggregateCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	rowAggregateCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "table_id" */
	rowAggregateCmd.Flags().StringVar(&rowAggregateCmdTableIdVar, "table-id", "", "Path parameter table_id")
	rowAggregateCmd.MarkFlagRequired("table-id")
	rowAggregateCmd.Flags().StringVar(&rowAggregateCmdAggsVar, "aggs", "", "Query param aggs")
	rowAggregateCmd.MarkFlagRequired("aggs")
	rowAggregateCmd.Flags().StringVar(&rowAggregateCmdFilterVar, "filter", "", "Query param filter")
	/* Path flag — Use: "project_id" */
	rowBulkCmd.Flags().StringVar(&rowBulkCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	rowBulkCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "table_id" */
	rowBulkCmd.Flags().StringVar(&rowBulkCmdTableIdVar, "table-id", "", "Path parameter table_id")
	rowBulkCmd.MarkFlagRequired("table-id")
	rowBulkCmd.Flags().StringVar(&rowBulkCmdDataVar, "data", "", "Request body: JSON literal, @file, or - for stdin")
	/* Path flag — Use: "project_id" */
	rowGetCmd.Flags().StringVar(&rowGetCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	rowGetCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "table_id" */
	rowGetCmd.Flags().StringVar(&rowGetCmdTableIdVar, "table-id", "", "Path parameter table_id")
	rowGetCmd.MarkFlagRequired("table-id")
	/* Path flag — Use: "row_id" */
	rowGetCmd.Flags().StringVar(&rowGetCmdRowIdVar, "row-id", "", "Path parameter row_id")
	rowGetCmd.MarkFlagRequired("row-id")
	/* Path flag — Use: "project_id" */
	rowUpdateCmd.Flags().StringVar(&rowUpdateCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	rowUpdateCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "table_id" */
	rowUpdateCmd.Flags().StringVar(&rowUpdateCmdTableIdVar, "table-id", "", "Path parameter table_id")
	rowUpdateCmd.MarkFlagRequired("table-id")
	/* Path flag — Use: "row_id" */
	rowUpdateCmd.Flags().StringVar(&rowUpdateCmdRowIdVar, "row-id", "", "Path parameter row_id")
	rowUpdateCmd.MarkFlagRequired("row-id")
	rowUpdateCmd.Flags().StringVar(&rowUpdateCmdDataVar, "data", "", "Request body: JSON literal, @file, or - for stdin")
	/* Path flag — Use: "project_id" */
	rowDeleteCmd.Flags().StringVar(&rowDeleteCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	rowDeleteCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "table_id" */
	rowDeleteCmd.Flags().StringVar(&rowDeleteCmdTableIdVar, "table-id", "", "Path parameter table_id")
	rowDeleteCmd.MarkFlagRequired("table-id")
	/* Path flag — Use: "row_id" */
	rowDeleteCmd.Flags().StringVar(&rowDeleteCmdRowIdVar, "row-id", "", "Path parameter row_id")
	rowDeleteCmd.MarkFlagRequired("row-id")
}
