// Code generated by honey. DO NOT EDIT.
package cmd

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"slices"
	"strings"
	"time"

	"github.com/spf13/cobra"

	cli "github.com/anyrow/cli/internal/cli"
	sdk "github.com/anyrow/cli/internal/sdk"
)

var _ = bytes.NewReader
var _ = context.TODO
var _ = json.Marshal
var _ = fmt.Sprintf
var _ = io.Discard
var _ = http.MethodGet
var _ = url.PathEscape
var _ = os.Stdout
var _ = slices.Contains[[]string]
var _ = strings.NewReader
var _ = time.Second
var _ = sdk.SSEEvent{}
var _ = cli.Version

var tableTemplateCmd = &cobra.Command{
	Use:   "table-template",
	Short: "Browse table templates",
}

var tableTemplateProjectListCmdProjectIdVar string
var tableTemplateProjectListCmdCursorVar string
var tableTemplateProjectListCmdFilterVar string
var tableTemplateProjectListCmdLangVar string
var tableTemplateProjectListCmdOrderVar string
var tableTemplateProjectListCmdPageVar int64
var tableTemplateProjectListCmdQVar string
var tableTemplateProjectListCmdSelectVar string
var tableTemplateProjectListCmdLimitVar int64

var tableTemplateProjectListCmd = &cobra.Command{
	Use:   "project-list",
	Short: "Browse table templates",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := tableTemplateProjectListCmdProjectIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/table-templates"
		q := url.Values{}
		if cmd.Flags().Changed("cursor") { q.Set("cursor", tableTemplateProjectListCmdCursorVar) }
		if cmd.Flags().Changed("filter") { q.Set("filter", tableTemplateProjectListCmdFilterVar) }
		if cmd.Flags().Changed("lang") { q.Set("lang", tableTemplateProjectListCmdLangVar) }
		if cmd.Flags().Changed("order") { q.Set("order", tableTemplateProjectListCmdOrderVar) }
		if cmd.Flags().Changed("page") { q.Set("page", fmt.Sprintf("%d", tableTemplateProjectListCmdPageVar)) }
		if cmd.Flags().Changed("q") { q.Set("q", tableTemplateProjectListCmdQVar) }
		if cmd.Flags().Changed("select") { q.Set("select", tableTemplateProjectListCmdSelectVar) }
		if cmd.Flags().Changed("limit") { q.Set("limit", fmt.Sprintf("%d", tableTemplateProjectListCmdLimitVar)) }
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		req, rerr := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
		if rerr != nil { return rerr }
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

var tableTemplateProjectGetCmdProjectIdVar string
var tableTemplateProjectGetCmdTemplateIdVar string

var tableTemplateProjectGetCmd = &cobra.Command{
	Use:   "project-get",
	Short: "Preview table template",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := tableTemplateProjectGetCmdProjectIdVar
		templateID := tableTemplateProjectGetCmdTemplateIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/table-templates/" + url.PathEscape(templateID)
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		req, rerr := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
		if rerr != nil { return rerr }
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

var tableTemplateUseCmdProjectIdVar string
var tableTemplateUseCmdTemplateIdVar string
var tableTemplateUseCmdDataVar string
var tableTemplateUseCmdNameVar string
var tableTemplateUseCmdSlugVar string

var tableTemplateUseCmd = &cobra.Command{
	Use:   "use",
	Short: "Create table from template",
	PreRunE: func(cmd *cobra.Command, args []string) error {
		if tableTemplateUseCmdDataVar == "" && !(cmd.Flags().Changed("name") || cmd.Flags().Changed("slug")) {
			return fmt.Errorf("body required: pass --data or per-field flags")
		}
		return nil
	},
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		projectID := tableTemplateUseCmdProjectIdVar
		templateID := tableTemplateUseCmdTemplateIdVar
		reqURL := baseURL + "/v1/projects/" + url.PathEscape(projectID) + "/table-templates/" + url.PathEscape(templateID) + "/use"
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		// merge --data + per-prop flags
		merged := map[string]any{}
		if tableTemplateUseCmdDataVar != "" {
			dataBytes, derr := cli.ReadDataFlag(tableTemplateUseCmdDataVar)
			if derr != nil { return derr }
			if len(dataBytes) > 0 {
				if jerr := json.Unmarshal(dataBytes, &merged); jerr != nil { return fmt.Errorf("parse --data: %w", jerr) }
			}
		}
		if cmd.Flags().Changed("name") { merged["name"] = tableTemplateUseCmdNameVar }
		if cmd.Flags().Changed("slug") { merged["slug"] = tableTemplateUseCmdSlugVar }
		bodyBytes, merr := json.Marshal(merged)
		if merr != nil { return merr }
		req, rerr := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(bodyBytes))
		if rerr != nil { return rerr }
		req.Header.Set("Content-Type", "application/json")
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

var tableTemplateCreateCmdDataVar string

var tableTemplateCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create table template",
	PreRunE: func(cmd *cobra.Command, args []string) error {
		if tableTemplateCreateCmdDataVar == "" && !(false) {
			return fmt.Errorf("body required: pass --data or per-field flags")
		}
		return nil
	},
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		reqURL := baseURL + "/v1/table-templates"
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		bodyBytes, derr := cli.ReadDataFlag(tableTemplateCreateCmdDataVar)
		if derr != nil { return derr }
		req, rerr := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(bodyBytes))
		if rerr != nil { return rerr }
		req.Header.Set("Content-Type", "application/json")
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

var tableTemplateListMineCmdCursorVar string
var tableTemplateListMineCmdFilterVar string
var tableTemplateListMineCmdLangVar string
var tableTemplateListMineCmdOrderVar string
var tableTemplateListMineCmdPageVar int64
var tableTemplateListMineCmdQVar string
var tableTemplateListMineCmdSelectVar string
var tableTemplateListMineCmdLimitVar int64

var tableTemplateListMineCmd = &cobra.Command{
	Use:   "list-mine",
	Short: "List my table templates",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		reqURL := baseURL + "/v1/table-templates/mine"
		q := url.Values{}
		if cmd.Flags().Changed("cursor") { q.Set("cursor", tableTemplateListMineCmdCursorVar) }
		if cmd.Flags().Changed("filter") { q.Set("filter", tableTemplateListMineCmdFilterVar) }
		if cmd.Flags().Changed("lang") { q.Set("lang", tableTemplateListMineCmdLangVar) }
		if cmd.Flags().Changed("order") { q.Set("order", tableTemplateListMineCmdOrderVar) }
		if cmd.Flags().Changed("page") { q.Set("page", fmt.Sprintf("%d", tableTemplateListMineCmdPageVar)) }
		if cmd.Flags().Changed("q") { q.Set("q", tableTemplateListMineCmdQVar) }
		if cmd.Flags().Changed("select") { q.Set("select", tableTemplateListMineCmdSelectVar) }
		if cmd.Flags().Changed("limit") { q.Set("limit", fmt.Sprintf("%d", tableTemplateListMineCmdLimitVar)) }
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		req, rerr := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
		if rerr != nil { return rerr }
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

var tableTemplateUpdateCmdTemplateIdVar string
var tableTemplateUpdateCmdDataVar string

var tableTemplateUpdateCmd = &cobra.Command{
	Use:   "update",
	Short: "Update table template",
	PreRunE: func(cmd *cobra.Command, args []string) error {
		if tableTemplateUpdateCmdDataVar == "" && !(false) {
			return fmt.Errorf("body required: pass --data or per-field flags")
		}
		return nil
	},
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		templateID := tableTemplateUpdateCmdTemplateIdVar
		reqURL := baseURL + "/v1/table-templates/" + url.PathEscape(templateID)
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		bodyBytes, derr := cli.ReadDataFlag(tableTemplateUpdateCmdDataVar)
		if derr != nil { return derr }
		req, rerr := http.NewRequestWithContext(ctx, "PATCH", reqURL, bytes.NewReader(bodyBytes))
		if rerr != nil { return rerr }
		req.Header.Set("Content-Type", "application/json")
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

var tableTemplateDeleteCmdTemplateIdVar string

var tableTemplateDeleteCmd = &cobra.Command{
	Use:   "delete",
	Short: "Delete table template",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()
		cfg := configFromCtx(ctx)
		apiKey, err := cli.ResolveAPIKey(cfg)
		if err != nil { return err }
		_ = apiKey
		baseURL := cfg.BaseURL
		if baseURL == "" { return fmt.Errorf("base URL required: set --base-url, env, or config") }
		timeout := 30 * time.Second
		if cfg.Timeout != "" {
			if d, perr := time.ParseDuration(cfg.Timeout); perr == nil { timeout = d }
		}
		httpClient := &http.Client{Timeout: timeout}
		templateID := tableTemplateDeleteCmdTemplateIdVar
		reqURL := baseURL + "/v1/table-templates/" + url.PathEscape(templateID)
		q := url.Values{}
		if len(q) > 0 { reqURL += "?" + q.Encode() }
		req, rerr := http.NewRequestWithContext(ctx, "DELETE", reqURL, nil)
		if rerr != nil { return rerr }
		if apiKey != "" { req.Header.Set("Authorization", "Bearer "+apiKey) }
		resp, herr := httpClient.Do(req)
		if herr != nil { return herr }
		defer resp.Body.Close()
		body, berr := io.ReadAll(resp.Body)
		if berr != nil { return berr }
		if resp.StatusCode >= 400 {
			return &sdk.StatusError{StatusCode: resp.StatusCode, Body: body, Response: resp, Message: string(body)}
		}
		var out any
		if len(body) > 0 {
			if jerr := json.Unmarshal(body, &out); jerr != nil { return jerr }
		}
		return cli.Emit(out, cfg.Output, os.Stdout)
	},
}

func init() {
	tableTemplateCmd.AddCommand(tableTemplateProjectListCmd)
	tableTemplateCmd.AddCommand(tableTemplateProjectGetCmd)
	tableTemplateCmd.AddCommand(tableTemplateUseCmd)
	tableTemplateCmd.AddCommand(tableTemplateCreateCmd)
	tableTemplateCmd.AddCommand(tableTemplateListMineCmd)
	tableTemplateCmd.AddCommand(tableTemplateUpdateCmd)
	tableTemplateCmd.AddCommand(tableTemplateDeleteCmd)
	/* Path flag — Use: "project_id" */
	tableTemplateProjectListCmd.Flags().StringVar(&tableTemplateProjectListCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	tableTemplateProjectListCmd.MarkFlagRequired("project-id")
	tableTemplateProjectListCmd.Flags().StringVar(&tableTemplateProjectListCmdCursorVar, "cursor", "", "Query param cursor")
	tableTemplateProjectListCmd.Flags().StringVar(&tableTemplateProjectListCmdFilterVar, "filter", "", "Query param filter")
	tableTemplateProjectListCmd.Flags().StringVar(&tableTemplateProjectListCmdLangVar, "lang", "", "Query param lang")
	tableTemplateProjectListCmd.Flags().StringVar(&tableTemplateProjectListCmdOrderVar, "order", "", "Query param order")
	tableTemplateProjectListCmd.Flags().Int64Var(&tableTemplateProjectListCmdPageVar, "page", 0, "Query param page")
	tableTemplateProjectListCmd.Flags().StringVar(&tableTemplateProjectListCmdQVar, "q", "", "Query param q")
	tableTemplateProjectListCmd.Flags().StringVar(&tableTemplateProjectListCmdSelectVar, "select", "", "Query param select")
	tableTemplateProjectListCmd.Flags().Int64Var(&tableTemplateProjectListCmdLimitVar, "limit", 20, "Query param limit")
	/* Path flag — Use: "project_id" */
	tableTemplateProjectGetCmd.Flags().StringVar(&tableTemplateProjectGetCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	tableTemplateProjectGetCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "template_id" */
	tableTemplateProjectGetCmd.Flags().StringVar(&tableTemplateProjectGetCmdTemplateIdVar, "template-id", "", "Path parameter template_id")
	tableTemplateProjectGetCmd.MarkFlagRequired("template-id")
	/* Path flag — Use: "project_id" */
	tableTemplateUseCmd.Flags().StringVar(&tableTemplateUseCmdProjectIdVar, "project-id", "", "Path parameter project_id")
	tableTemplateUseCmd.MarkFlagRequired("project-id")
	/* Path flag — Use: "template_id" */
	tableTemplateUseCmd.Flags().StringVar(&tableTemplateUseCmdTemplateIdVar, "template-id", "", "Path parameter template_id")
	tableTemplateUseCmd.MarkFlagRequired("template-id")
	tableTemplateUseCmd.Flags().StringVar(&tableTemplateUseCmdDataVar, "data", "", "Request body: JSON literal, @file, or - for stdin")
	tableTemplateUseCmd.Flags().StringVar(&tableTemplateUseCmdNameVar, "name", "", "Body field name")
	tableTemplateUseCmd.Flags().StringVar(&tableTemplateUseCmdSlugVar, "slug", "", "Body field slug")
	tableTemplateCreateCmd.Flags().StringVar(&tableTemplateCreateCmdDataVar, "data", "", "Request body: JSON literal, @file, or - for stdin")
	tableTemplateListMineCmd.Flags().StringVar(&tableTemplateListMineCmdCursorVar, "cursor", "", "Query param cursor")
	tableTemplateListMineCmd.Flags().StringVar(&tableTemplateListMineCmdFilterVar, "filter", "", "Query param filter")
	tableTemplateListMineCmd.Flags().StringVar(&tableTemplateListMineCmdLangVar, "lang", "", "Query param lang")
	tableTemplateListMineCmd.Flags().StringVar(&tableTemplateListMineCmdOrderVar, "order", "", "Query param order")
	tableTemplateListMineCmd.Flags().Int64Var(&tableTemplateListMineCmdPageVar, "page", 0, "Query param page")
	tableTemplateListMineCmd.Flags().StringVar(&tableTemplateListMineCmdQVar, "q", "", "Query param q")
	tableTemplateListMineCmd.Flags().StringVar(&tableTemplateListMineCmdSelectVar, "select", "", "Query param select")
	tableTemplateListMineCmd.Flags().Int64Var(&tableTemplateListMineCmdLimitVar, "limit", 20, "Query param limit")
	/* Path flag — Use: "template_id" */
	tableTemplateUpdateCmd.Flags().StringVar(&tableTemplateUpdateCmdTemplateIdVar, "template-id", "", "Path parameter template_id")
	tableTemplateUpdateCmd.MarkFlagRequired("template-id")
	tableTemplateUpdateCmd.Flags().StringVar(&tableTemplateUpdateCmdDataVar, "data", "", "Request body: JSON literal, @file, or - for stdin")
	/* Path flag — Use: "template_id" */
	tableTemplateDeleteCmd.Flags().StringVar(&tableTemplateDeleteCmdTemplateIdVar, "template-id", "", "Path parameter template_id")
	tableTemplateDeleteCmd.MarkFlagRequired("template-id")
}
